version: "3.9"

services:

  assistant_handler:
    build: .
    container_name: assistant_handler
    env_file:
      - ../.env
    networks:
      - es_external_network

  nginx:
    image: nginx:latest
    container_name: assistant_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - assistant_handler
    ports:
      - "8003:82"
    networks:
      - es_external_network

networks:
  es_external_network:
    external: true
